# Generated by Django 4.2.30 on 2026-07-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_accepteditemcategory_alter_servicetype_options_and_more'),
        ('schedules', '0002_dropofflocation_shipmentschedule_and_more'),
        ('logistics', '0005_merge_20260626_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='accepted_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='services.accepteditemcategory'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='schedules.dropofflocation'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='item_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='phones_without_battery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='route_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='services.routeoption'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='shipment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='schedules.shipmentschedule'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='shopping_assistance_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='shopping_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['reference_code'], name='logistics_t_referen_09c01c_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['status', 'created_at'], name='logistics_t_status_0ae1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['route_option', 'status'], name='logistics_t_route_o_3efb71_idx'),
        ),
    ]
