# Generated by Django 4.2.30 on 2026-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('requires_battery_removed', models.BooleanField(default=False)),
                ('route_restriction', models.CharField(blank=True, choices=[('', 'No route restriction'), ('germany_cameroon', 'Germany or Europe to Cameroon only'), ('cameroon_germany', 'Cameroon to Germany or Europe only')], default='', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.CreateModel(
            name='RouteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('direction', models.CharField(choices=[('germany_cameroon', 'Germany or Europe to Cameroon'), ('cameroon_germany', 'Cameroon to Germany or Europe')], max_length=40)),
                ('origin_label', models.CharField(max_length=120)),
                ('destination_label', models.CharField(max_length=120)),
                ('transit_time_display', models.CharField(blank=True, help_text='Customer-facing wording, e.g. "3 - 10 days". Keep configurable because source materials conflict.', max_length=120)),
                ('shopping_assistance_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['active', 'direction'], name='services_ro_active_b5eac0_idx'), models.Index(fields=['sort_order'], name='services_ro_sort_or_89b78e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='routeoption',
            constraint=models.UniqueConstraint(fields=('direction', 'origin_label', 'destination_label'), name='unique_route_direction_origin_destination'),
        ),
        migrations.AddIndex(
            model_name='accepteditemcategory',
            index=models.Index(fields=['active', 'sort_order'], name='services_ac_active_d4b1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='accepteditemcategory',
            index=models.Index(fields=['route_restriction'], name='services_ac_route_r_8464e2_idx'),
        ),
    ]
