# Generated by Django 4.2.30 on 2026-07-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_accepteditemcategory_alter_servicetype_options_and_more'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('drop_off', 'Drop-off'), ('pickup', 'Pickup'), ('both', 'Drop-off and pickup')], default='drop_off', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('whatsapp', models.CharField(blank=True, max_length=80)),
                ('opening_hours', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'country', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('latest_dropoff_at', models.DateTimeField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('estimated_arrival_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop_off_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_schedules', to='schedules.dropofflocation')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_schedules', to='services.routeoption')),
            ],
            options={
                'ordering': ['latest_dropoff_at', 'departure_date', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='dropofflocation',
            index=models.Index(fields=['active', 'country', 'city'], name='schedules_d_active_e9af7e_idx'),
        ),
        migrations.AddIndex(
            model_name='dropofflocation',
            index=models.Index(fields=['location_type', 'active'], name='schedules_d_locatio_ce1dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentschedule',
            index=models.Index(fields=['active', 'departure_date'], name='schedules_s_active_6b4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentschedule',
            index=models.Index(fields=['active', 'latest_dropoff_at'], name='schedules_s_active_38dec4_idx'),
        ),
    ]
