export const ncklConfig = {
  companyName: process.env.NEXT_PUBLIC_COMPANY_NAME || "NCKL Logistics Services",
  shortName: process.env.NEXT_PUBLIC_SHORT_NAME || "NCKL",
  slogan: "Your Cargo. Our Commitment.",
  sloganFr: "Votre Cargaison. Notre Engagement.",
  primaryWhatsApp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "+4915212392636",
  supportEmail: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "",
  tikTokHandle: process.env.NEXT_PUBLIC_TIKTOK_HANDLE || "@nckllogisticsservices",
  routeLabels: ["Germany/Europe to Cameroon", "Cameroon to Germany/Europe"],
  dropOffCities: ["Bamenda", "Douala", "Berlin", "Leipzig"],
  acceptedItems: [
    "Foodstuff (dry)",
    "Frozen food",
    "Clothes",
    "Jewelries",
    "Bags",
    "Shoes",
    "Cosmetics",
    "Hair extensions",
    "Dry herbs",
    "Documents",
    "Phones without battery",
    "Small household equipment up to 31 kg",
  ],
  locations: [
    {
      city: "Bamenda",
      label: "Commercial avenue entrance to the stadium, Shed A7",
      contact: "+237 674574041 / +237 622441020",
      hours: "Tuesday - Saturday, 11am - 3pm",
    },
    {
      city: "Douala",
      label: "Bonaberi, Rue 4.670 / Nouvelle route Bonaberi",
      contact: "+237 675745056 / +237 674972802",
      hours: "Call or WhatsApp",
    },
    {
      city: "Berlin",
      label: "Eichushallee 53 Apartment 227, 12437 Berlin",
      contact: "+49 15222376184",
      hours: "WhatsApp only",
    },
    {
      city: "Leipzig",
      label: "Ariana Mark Leipzig, Rosa-Luxemburg Strasse 10, 04103 Leipzig",
      contact: "+49 15773620710",
      hours: "Monday - Saturday",
    },
  ],
} as const;
