export const ncklConfig = {
  companyName: process.env.NEXT_PUBLIC_COMPANY_NAME || "NCKL Logistics Services",
  shortName: process.env.NEXT_PUBLIC_SHORT_NAME || "NCKL",
  slogan: "Your Cargo. Our Commitment.",
  sloganFr: "Votre Cargaison. Notre Engagement.",
  primaryWhatsApp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "+4915212392636",
  supportEmail: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "",
  tikTokHandle: process.env.NEXT_PUBLIC_TIKTOK_HANDLE || "@nckllogisticsservices",
  routeLabels: ["Germany/Europe to Cameroon", "Cameroon to Germany/Europe"],
  dropOffCities: ["Bamenda", "Douala", "Berlin", "Leipzig"],
  acceptedItems: [
    "Foodstuff (dry)",
    "Frozen food",
    "Clothes",
    "Jewelries",
    "Bags",
    "Shoes",
    "Cosmetics",
    "Hair extensions",
    "Dry herbs",
    "Documents",
    "Phones without battery",
    "Small household equipment up to 31 kg",
  ],
} as const;
